// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: mode_queries.sql

package sqlc

import (
	"context"
)

const listModes = `-- name: ListModes :many
SELECT id, name FROM mode
`

func (q *Queries) ListModes(ctx context.Context) ([]Mode, error) {
	rows, err := q.db.QueryContext(ctx, listModes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mode
	for rows.Next() {
		var i Mode
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
