// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Mode struct {
	ID   int64
	Name sql.NullString
}

type Trip struct {
	ID       int64
	Name     sql.NullString
	Distance int32
	Mode     sql.NullInt32
}
